In [1]:
import lib
from grid import GridWorldC

In [2]:
env = GridWorldC()

# QLearning

In [3]:
q_learning = lib.QLearning(env, 1000000)
q_table = q_learning.run()
print(q_table)

[[ 6.91914025e-310  1.90851381e+294  1.92928840e-316  1.94727033e+282]
 [ 6.91913539e-310  1.88942867e+300              nan  2.17491003e+204]
 [ 2.27270197e-322              nan  2.15316093e+210  2.06830526e+246]
 [ 1.69759663e-313  2.08919097e+252  4.94065646e-324              nan]
 [             nan              nan  2.06829906e+258  1.69759663e-313]
 [ 1.88942675e+300  1.96693572e+276  1.03753786e-322  2.04762430e+252]
 [ 1.90851576e+294  2.06830526e+246  2.06830948e+246 -1.98680383e+276]
 [ 2.04762221e+252  2.00687657e+264  2.04762430e+252 -1.96693580e+282]
 [-2.11030028e+240  1.98680781e+270  1.98680781e+270              nan]
 [             nan              nan  2.08920150e+240  5.51718906e-313]
 [ 2.06830948e+246  1.98680375e+270  1.92875165e-316 -2.06830323e+252]
 [ 2.04762430e+252  4.76186573e+156  2.45369337e+132  2.08920150e+240]
 [ 1.94727033e+282 -2.15314577e+228  2.11030454e+234  1.90851965e+294]
 [ 2.21906290e+204  2.21907178e+192  1.92779763e+288              nan]
 [    

In [4]:
import numpy as np
import lib

# Assuming 'env' is an instance of your environment class with necessary methods
q_learning = lib.QLearning(env, 1000000)
q_table = q_learning.run()

def extract_policy_from_q_table(q_table, grid_shape):
    policy = {}
    num_states, num_actions = q_table.shape
    
    for state in range(num_states):
        best_action = np.argmax(q_table[state])
        policy[(state // grid_shape[1], state % grid_shape[1])] = best_action
    return policy

def print_policy(policy, grid_size):
    policy_arrows = {
        0: '←',  # Gauche
        1: '→',  # Droite
        2: '↑',  # Haut
        3: '↓'   # Bas
    }

    grid = np.full(grid_size, ' ')
    for (state, action) in policy.items():
        row, col = state
        grid[row, col] = policy_arrows[action]

    for row in grid:
        row_str = ' '.join(row).strip()
        if row_str:
            print(row_str)

# Assurez-vous que la Q-table a la bonne structure
print(q_table)

# Extraire la politique de la Q-table
grid_shape = (5, 5)  # Taille de la grille
policy = extract_policy_from_q_table(q_table, grid_shape)

# Imprimer la politique
print_policy(policy, grid_shape)


[[ 4.71882098e-320  1.63588074e+144  0.00000000e+000  1.63587992e+144]
 [ 6.36598737e-313  1.58729265e+162  3.40564407e-013  1.65240396e+138]
 [ 1.06099790e-313  1.60332591e+156  1.63587825e+144 -3.58115286e-037]
 [ 0.00000000e+000  3.01868366e+059  8.51451724e+113  3.07998145e+047]
 [ 0.00000000e+000  3.11109238e+041  8.95336427e+071  8.48798316e-313]
 [ 9.04382075e+065  1.61952194e+150  0.00000000e+000  1.65240479e+138]
 [ 1.66909659e+132  1.60332591e+156  1.63587992e+144  1.60332427e+156]
 [ 1.61951781e+150  8.68739643e+101  1.61952112e+150  5.91721181e+083]
 [ 2.98849377e+077  8.77515687e+095  3.50989494e-031  2.98849683e+065]
 [ 3.07998145e+047  3.40564755e-013  3.01868674e+059  5.51718906e-313]
 [ 1.63588074e+144  2.96999406e+018  0.00000000e+000  1.60332672e+156]
 [ 1.61952112e+150  8.34506984e+125  1.61952194e+150  8.68740530e+101]
 [ 8.77515687e+095  1.57141972e+168  1.60332591e+156  2.92902574e+077]
 [ 2.95861186e+071  8.51450856e+113  8.86379481e+089  9.41480149e+041]
 [ 3.4

In [5]:
monte_carlo_es = lib.MonteCarloES(env, 10000)
value_table = monte_carlo_es.run()
print(value_table)

{19: 0.12709475491899833, 18: -0.32069558550249894, 22: -0.8396678460067803, 23: -0.07756391931387115, 11: -1.0744000130436047, 10: -1.3331963535055984, 15: -1.8929205219248657, 0: -0.9274288706150202, 5: -1.043762570961903, 6: -0.9082943614724224, 21: -1.7171847986759279, 8: -0.5340534724962173, 16: -1.3545997987763223, 3: -0.563600611128293, 17: -0.8222465137242504, 4: -0.4909904189259837, 12: -0.7603747564920726, 9: -0.42524368165174914, 14: -0.2542224609085387, 1: -0.8426172126792837, 13: -0.4624302264307895, 7: -0.7195273974251114, 2: -0.7107929128801914}


In [6]:
mcoffpolicy = lib.OffPolicyMonteCarloControl(env, 10000)
value_table = mcoffpolicy.run()
print(value_table)

{21: {2: -3.0}, 19: {1: 1.0}, 15: {1: -3.0}, 23: {3: 1.0}}


In [7]:
onpolicy_mc_control = lib.onPolicyMonteCarloControl(env, 10)
q_table = onpolicy_mc_control.run()
print(q_table)

{21: {0: 2.47e-322}, 23: {2: 6.399264795364105e-234, 0: -4.834547968532139e-216}, 0: {1: -1.0383281242402132e-24, 3: -2.320144793844425e-24}, 1: {1: -2.3435448018206303e-24, 3: -2.6440407146021305e-24, 2: -5.2144152923355216e-20}, 2: {1: -2.952991886875015e-24, 2: -2.6706420096118683e-24, 3: -3.0742647186835076e-24}, 4: {1: -3.1018523578107766e-23, 2: -7.978301497733588e-23}, 3: {3: -3.357961666538628e-22, 1: -3.105317867746352e-24, 2: -3.7969337397788435e-24}, 6: {0: -2.3672159011143743e-24, 3: -1.6303156488594055e-23, 2: -2.098291485574776e-24, 1: -2.836660542525747e-24}, 5: {0: -1.0488162770080018e-24, 3: -2.077287782865724e-24, 1: -1.1342224679821949e-24}, 9: {1: -3.4646862469585014e-23, 0: -3.0708343816670785e-23, 2: -3.195067162898508e-22}, 15: {3: -0.0003233391074987005, 0: -1.4119806306618744e-25, 1: -3.0}, 22: {0: -2.1879357412405126e-37}, 17: {2: 4.061388785183605e-102, 0: -1.97037090936045e-17, 3: -3.04088e-319, 1: -3.2490846070408327e-37}, 16: {1: 2.47e-322, 0: -5.802882018

In [8]:
dyna_Q = lib.DynaQ(env, 10000)
q_table = dyna_Q.run()
print(q_table)

Episode 1: Total Reward: 1, Exploration Rate: 0.995
Episode 2: Total Reward: -3, Exploration Rate: 0.990025
Episode 3: Total Reward: 1, Exploration Rate: 0.985075
Episode 4: Total Reward: -3, Exploration Rate: 0.98015
Episode 5: Total Reward: -3, Exploration Rate: 0.975249
Episode 6: Total Reward: -3, Exploration Rate: 0.970373
Episode 7: Total Reward: -3, Exploration Rate: 0.965521
Episode 8: Total Reward: -3, Exploration Rate: 0.960693
Episode 9: Total Reward: 1, Exploration Rate: 0.95589
[[ 4.71882098e-320  5.69752927e+147  0.00000000e+000  5.71825460e+147]
 [ 6.36598737e-313  5.72895183e+147  5.67424020e+147  5.68020380e+147]
 [ 1.06099790e-313  5.69423632e+147  5.69813689e+147  5.70290340e+147]
 [ 0.00000000e+000  5.71368302e+147  5.68384987e+147  5.69589603e+147]
 [ 0.00000000e+000  5.70473538e+147  5.68953647e+147  8.48798316e-313]
 [ 5.70295558e+147  5.67000081e+147  0.00000000e+000  5.71078918e+147]
 [ 5.74681468e+147  5.70962535e+147  5.70079081e+147  5.70428575e+147]
 [ 5.69

In [9]:
sarsa = lib.SARSA(env, 10000)
q_table = sarsa.run()
q_table

State: 0, Action: 1, Reward: 0, Next State: 5, Next Action: 0
Q(0, 1) updated to: 0
State: 5, Action: 0, Reward: 0, Next State: 0, Next Action: 1
Q(5, 0) updated to: 0
State: 0, Action: 1, Reward: 0, Next State: 5, Next Action: 1
Q(0, 1) updated to: 0
State: 5, Action: 1, Reward: 0, Next State: 10, Next Action: 1
Q(5, 1) updated to: 0
State: 10, Action: 1, Reward: 0, Next State: 15, Next Action: 1
Q(10, 1) updated to: 0
State: 15, Action: 1, Reward: -3, Next State: 20, Next Action: 3
Q(15, 1) updated to: -30000
Episode 1: Total Reward: -3, Exploration Rate: 0.995
State: 0, Action: 3, Reward: 0, Next State: 1, Next Action: 3
Q(0, 3) updated to: 0
State: 1, Action: 3, Reward: 0, Next State: 2, Next Action: 1
Q(1, 3) updated to: 0
State: 2, Action: 1, Reward: 0, Next State: 7, Next Action: 3
Q(2, 1) updated to: 0
State: 7, Action: 3, Reward: 0, Next State: 8, Next Action: 3
Q(7, 3) updated to: 0
State: 8, Action: 3, Reward: 0, Next State: 9, Next Action: 2
Q(8, 3) updated to: 0
State: 9, 

array([[ 0.000e+00,  1.000e+10,  0.000e+00, -1.000e+10],
       [ 0.000e+00,  0.000e+00,  1.000e+10,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [-1.000e+10, -1.000e+10,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00, -1.000e+10,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  9.900e+07,  0.000e+00,  0.000e+00],
       [-1.000e+10,  1.000e+10,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00, -1.000e+10,  0.000e+00],
       [ 0.000e+00,  0.000e+00,

Next State: 12, Next Action: 1
Q(17, 0) updated to: 0
State: 12, Action: 1, Reward: 0, Next State: 17, Next Action: 0
Q(12, 1) updated to: 0
State: 17, Action: 0, Reward: 0, Next State: 12, Next Action: 2
Q(17, 0) updated to: 0
State: 12, Action: 2, Reward: 0, Next State: 11, Next Action: 3
Q(12, 2) updated to: 0
State: 11, Action: 3, Reward: 0, Next State: 12, Next Action: 1
Q(11, 3) updated to: 0
State: 12, Action: 1, Reward: 0, Next State: 17, Next Action: 3
Q(12, 1) updated to: 0
State: 17, Action: 3, Reward: 0, Next State: 18, Next Action: 2
Q(17, 3) updated to: 0
State: 18, Action: 2, Reward: 0, Next State: 17, Next Action: 1
Q(18, 2) updated to: 0
State: 17, Action: 1, Reward: 0, Next State: 22, Next Action: 3
Q(17, 1) updated to: 0
State: 22, Action: 3, Reward: 0, Next State: 23, Next Action: 0
Q(22, 3) updated to: 0
State: 23, Action: 0, Reward: 0, Next State: 18, Next Action: 3
Q(23, 0) updated to: 0
State: 18, Action: 3, Reward: 0, Next State: 19, Next Action: 0
Q(18, 3) upd

In [10]:
policy_iteration = lib.PolicyIteration(GridWorldC)
policy, V = policy_iteration.run()
print(policy)
for i in range(len(V)):
    print(V[i], end=" ")
    if i % 5 == 4:
        print()

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0]
0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 1.0 
0.0 0.0 0.0 1.0 0.0 


In [11]:
value_iteration = lib.ValueIteration(GridWorldC)
value = value_iteration.run()
for i in range(len(value)):
    print(value[i], end=" ")
    if i % 5 == 4:
        print()

0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 1.0 
0.0 0.0 0.0 1.0 0.0 
